### PR TITLE
auth-oauth: Use Helpdesk URL for redirect

### LINKED ISSUE #52: [auth-oauth Google+] Allow https in redirect url
Redirect URL is hard coded in plugin for use "http".

auth-oauth/google.php:

```
->set('redirect', 'http://' . $_SERVER['HTTP_HOST']
```

### PR DESCRIPTION
**Pull request by lubo**
Fixes #52.

### CODE REVIEW

**Comment by lubo** [comment]
@greezybacon @protich Could you take a look at this change, please ?

**Comment by ntozier** [comment]
You would want to ping @rayfoss and @JediKev for that to happen.

**Comment by lubo** [comment]
Common guys, it's been almost a month already. What is going on ?

**Comment by FossPrime** [comment]
works great

**Comment by mckaygerhard** [comment]
great plugin feature, bad osticket attention..

great work @lubo

**Comment by lubo** [comment]
Closing as the affected plugin is obsolete.

**Pull request closed without merging**
