### PR TITLE
Add support for CAS authentication

### PR DESCRIPTION
**Pull request by kevinoconnor7**
I have added support for [Jasig CAS](http://www.jasig.org/cas) as an auth provider. CAS is popular at higher education institutions.

Implementation is kind-of similar to the oauth provider.

### CODE REVIEW

**Comment by wrighrc** [comment]
Any idea if this pull request will be merged?    We are interested in CAS with osTicket.

**Comment by kevinoconnor7** [comment]
Considering how long this PR has been out, I'm doubtful. I also haven't really tested it lately, but I haven't heard any issues of it failing in the one place I deployed it. Feel free to clone the repo, switch to my branch, compile my plugin and install it yourself. Let me know if you need help with that.

**Comment by jjsipahigil** [comment]
I would also like to voice my support for merging this back in—you're definitely right about CAS and higher ed.

**Comment by kevinoconnor7** [comment]
I just did a small update to the PR. In addition, since people are interested in this I have written a [blog post](https://kevin.oconnor.io/code/2015/03/29/jasig-cas-for-osticket/) detailing how to install it in the meantime.

**Comment by kevinoconnor7** [comment]
I have added support for i18n, however I don't suspect that this PR is ever going to be merged in. As such I'm going to close this PR and put my plugin into its own [repository](https://github.com/kevinoconnor7/osTicket-auth-cas). Further updates will be found there.

**Comment by greezybacon** [comment]
@kevinoconnor7 one of the issues I've yet to figure is dealing with fixes to the plugin. I suppose we should get going merging in others' plugins and figure that part out later. I'm happy to see your associated repo. I'd like to consider merging it here, but connecting to it via a Git submodule may be a better idea in the future.

**Comment by kevinoconnor7** [comment]
I'm not sure merging this in at this point is the best idea. This branch is now behind the new repo. I can follow up with another PR to bring it up to date tonight if you wish. Though I think this might become burdensome if more plugins get merged in here and things start to diverge.

If you want to pursue a more accessible plugin system then it might be worth making a repository that contains a registry of _approved_ plugins and their associated repos. You could probably hook it up to travis so you can build them, sign them, and host them on bintray or something. Then build out a small utility for osTicket that will fetch them and drop the signed phars into the plugin folder. Ideally I would then only need to bump a version number in this registry when I do a new release.

**Comment by kevinoconnor7** [comment]
Woops, look like you merged. I'll follow up later tonight to bring things up to date.

**Comment by greezybacon** [comment]
No worries. I can merge a branch from your repo. Which one?

Cheers,
Jared

Am Donnerstag, 30. Juli 2015 schrieb kevinoconnor7 :

**Comment by kevinoconnor7** [comment]
Merge in at tag v1.0, which I believe is current HEAD and where the master
branch is. It's a bit tricky though because I have other files in there as
well (ex. my tavis CI config) so just make sure you grab only the auth_cas
folder.

**Pull request merged**
