### PR TITLE
Password Policy Plugin

### PR DESCRIPTION
**Pull request by protich**
Extends and generalizes PR #60 made by Jared. Notabled changes include;

* Make plugin generic password policy management  plugin as opposed to just
password complexity plugin
* Support both class of characters AND password strength checking
* Support checking policy on login
* Support ability to expire passwords 

This plugin requires core changes in PR #[5561](https://github.com/osTicket/osTicket/pull/5561 ).

Here is a preview of plugin configuration page.

Plugin Config Page

### CODE REVIEW

**Comment by chalithcp** [comment]
@protich 

Could you please let us know, how to apply this. 

I upgraded my platform to v1.14.3. I tried adding this as a plugin. Copied auth.php and plugin.php in to plugin folder. Added it as a new plugin. Just after installing new plugin, site is not loading. after removing above two files only i could load the site. 

Could you please support. 

Thanks.

**Comment by JediKev** [comment]
@chalithcp 

It states in the Pull Request message:
>This plugin requires core changes in PR [#5561](https://github.com/osTicket/osTicket/pull/5561)

Cheers.

**Comment by chalithcp** [comment]
@JediKev 

I checked all the 12 files in PR #5561 and merged required changes with files in version v1.14.3. It is working. I really appreciate the effort. 

I would like to know, do we really need to do the required core changes manually or will it be updated in next OSticket versions ?

Thanks.

**Comment by JediKev** [comment]
@chalithcp 

Once it is merged it will be included in the following release.

Cheers.

**Pull request merged**
