### PR TITLE
increase path size limit and box size

### PR DESCRIPTION
**Pull request by ntozier**
path length too short, increased to 120 characters.  Also increased size of text field box.

### CODE REVIEW

**Comment by greezybacon** [comment]
120 on the "size" seems a bit much. Maybe 80?

**Comment by ntozier** [comment]
I was going to go with 80 originally.  But the more I thought about it many web host use paths like this:

/home/username/public_html/www.domainname.ext
or
/home/username/webservice/domainname.ext 
or
c:\inetpub\vhosts\domain.tld\httpdocs
or similar.  Since domain names have a maximum length of 253 characters arguably this path could get extremely long.  Generally people prefer shorter domain names so I feel that most use cases will be about a quarter to half that size over all.  Thus why I picked 120.

**Comment by greezybacon** [comment]
I don't mind 250 for the length property. The size property is the display size for the widget. I think most paths should fit in a smaller box. I feel like a box with size=120 will seem unnecessarily enormous on the screen

**Comment by greezybacon** [comment]
And for the record, relative paths (those not starting with a slash or drive specification (c:)) are considered relative to the osTicket install root

**Comment by greezybacon** [comment]
Merged. Thanks for posting the issue

**Pull request closed without merging**
