### PR TITLE
Added scopes needed by O365

### PR DESCRIPTION
**Pull request by softcodex-team**
configuring email in admin panel to download ticket and send email (pop/imap/smtp) needed to add additionals scopes

### CODE REVIEW

**Comment by JediKev** [comment]
@softcodex-team 

You do not need those scopes in the configuration as the `Mail.ReadWrite` covers it. You do need those API Permissions however.

Cheers.

**Comment by softcodex-team** [comment]
only with Mail.ReadWrite, after save the email account, got an error of authorization

**Comment by JediKev** [comment]
@softcodex-team 

Did you follow the steps in our documentation? Also, if you need to edit the scopes, no need to make a pull request, you can just manually add them in the field. The default scopes we have now are working for many, many O365 setups.

Cheers.

**Comment by softcodex-team** [comment]
yess followed the doc!
no problem, I thought the defaults are changed!
thanks anyway! a pull request extends life 😂

**Pull request closed without merging**
