### PR TITLE
ldap: Allow specification of extremely long DNs

### LINKED ISSUE #9: AD PLUGIN CONFIG PAGE
The "Search User:" field is too short. 
Cannot set the DN of the user to querying LDAP

### PR DESCRIPTION
**Pull request by greezybacon**
Previously the DN length was capped at 80 chars. This patch allows specification of up to 120 chars.

Fixes #9

### CODE REVIEW

**Comment by cervedgroup** [comment]
how can i fix it ? where can i download tha patched .phar ?
thank you

**Comment by ntozier** [comment]
Click on the Files Changed at the top and it will show you what files changed and how they changed.

**Comment by cervedgroup** [comment]
i saw it, but if i change the .pahr file according with the info,  in my installation i got a signature error ...

**Comment by ntozier** [comment]
It says to edit  include/plugins/auth-ldap/config.php.  It does not say anything about changing a .phar file.  So I have no idea what your saying.

**Comment by cervedgroup** [comment]
THIS FILE : include/plugins/auth-ldap/config.php doesn't exists ...
 i only have the auth-ldap.phar into include/plugins
also the auth.ldap directory doesn't exist ...

**Comment by ntozier** [comment]
https://github.com/osTicket/core-plugins

**Pull request merged**
