### PR TITLE
ldap: Fix client login under some circumstances

### PR DESCRIPTION
**Pull request by greezybacon**

### CODE REVIEW

**Comment by AustinSaintAubin** [comment]
Testing now.

**Comment by AustinSaintAubin** [comment]
I cannot get package to build. Dependencies will not download, and I cannot seem to get the correct dependencies manually. 

---

.....
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear-pear/net_ldap2 could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
  ...

**Comment by Chefkeks** [comment]
Don't do this too complicated ;)

Just download the already build phar from osticket.com/download, extract it, replace the changed file(s), re-create the phar and use it. Did that several times and can't imagine an easier process ;)

**Comment by AustinSaintAubin** [comment]
Sorry, did not realize you had published the change to http://osticket.com/download 
Though the change was only in the development branch.
Downloading and testing ldap plugin from http://osticket.com/download/go?dl=plugin%2Fauth-ldap.phar

**Comment by AustinSaintAubin** [comment]
Still only able to authenticate with email and not samAccountName.
version = 0.5

**Comment by Chefkeks** [comment]
I had not publish it, instead I suggested to download, extract, replace the changed files and rebuild the phar. And btw. I am not an osTicket developer - just being helpful.

**Comment by AustinSaintAubin** [comment]
I have been playing with how to repackage / package phar's for a while now... whats your trick?

**Comment by Chefkeks** [comment]
Basically it's pretty easy ;)

To extract:
php -r '$phar = new Phar("auth-passthru.phar"); $phar->extractTo("./directory");'

To re-pack:
php -r '$phar = new Phar("auth-passthru.phar"); $phar->buildFromDirectory("./directory");'

Using this under linux and hope the syntax works under Windows too.

**Comment by AustinSaintAubin** [comment]
Thankyou @greezybacon your pach worked.
Users are able to login with email or account name as per LDAP with your changes to authentication.php.

Thankyou @Chefkeks I was able to repack with your help
Used code below to repack.

```
php -r '$phar = new Phar("auth-ldap.phar"); $phar->buildFromDirectory("./auth-ldap");' -c /Volumes/Macintosh\ HD/Applications/MAMP/bin/php/php5.6.6/conf/php.ini
```

**Comment by Chefkeks** [comment]
Great!

**Comment by greezybacon** [comment]
@AustinSaintAubin thanks for taking the time to test it out

**Comment by AustinSaintAubin** [comment]
@greezybacon thanks to the fix. @Chefkeks thanks for the help.

**Pull request merged**
